### ISSUE TITLE
iOS8崩溃解决思路

### ISSUE THREAD

**Issue by CaiChenghan** [coderAs7/HeaderScaleImage#1]
**问题描述**：此类在iOS8上会崩溃。
**问题原因**：因为扩展类的dealloc方法优先级高于类的dealloc方法。而iOS9开始，若类实现了dealloc方法，则也会执行。故iOS8崩溃，iOS9则没有问题。
**解决方法**：解决方法有三种，第一种，则是将此扩展类dealloc的方法，让其调用者来主动执行，方法笨拙。第二种，则是写一个新的scrollView集成UIScrollView。例如HeaderScrollView的类，扩展的是新建的类，例如HeaderScrollView+HeaderScaleImage。然后使用的时候，需要有次功能的类，都继承HeaderScrollView，这样就避免了在iOS8上“覆盖”dealloc方法了。第三种，则是将dealloc的代码，由willMoveToSuperview这个方法来执行，避开dealloc方法占用问题。
**总结**：源码不是很多，但写的不是很好。为什么？首先从思路来说，是利用runtime进行方法交换，交换的是tableView的setHeaderView这个方法。这就很有问题了，干嘛要影响到tableView的headerView？那headerView怎么办？故，**好的思路，应该是给scrollView绑定一个放大的view，与headerView无关**。其次从代码质量上，此类为对UIScrollView的扩展，但实际上，确实对UITableView的扩展，从方法交换的第一句代码即可看出。所以，写代码要严谨，挖的坑要填完。

**Comment by coderAs7** [comment]
此类经过测试,在iOS8上并不会崩溃.如果真的遇到了崩溃,请提供奔溃的iOS具体系统号.
此demo并没有使用runtime进行方法交换,所以没有影响到setHeaderView方法.
为了避免占用dealloc方法,此类中已经采取了您提到的方法三.
要不您重新下载仔细看看?确实没有您说的这些问题!
